# -*- coding: utf-8 -*-
{
    'name': "Z Stock",
    'summary': "Z Stock",
    'description': """""",
    'author': "",
    'website': "",
    'category': 'Inventory/Inventory',
    'version': '0.1',
    'depends': ['stock', 'product'],
    "license": "LGPL-3",
    'data': [
        'security/ir.model.access.csv',
        'data/ir_sequence.xml',
        'data/data.xml',
        'views/product_brand_view.xml',
        'views/product_line_view.xml',
        'views/product_gender_view.xml',
        'views/account_tax_view.xml',
        'views/price_list_view.xml',
        'views/res_currency_view.xml',
        'views/stock_document_and_accounting_view.xml',
        'views/erp_product_attribute_set_view.xml',
        'views/product_attribute_view.xml',
        'views/product_template_view.xml',
        'views/stock_quant_package_view.xml',
        'views/menu_view.xml',
        'views/erp_hr_department.xml',
        'views/erp_charge.xml',
        'views/erp_res_company.xml',
        'views/stock_customs_declaration.xml',
        'views/erp_views/erp_barcode_view.xml',
    ],
}
